### ISSUE TITLE
requirements issue 

### ISSUE THREAD

**Issue by ahmedkamal00** [D4Vinci/Dr0p1t-Framework#1]
when installing requirements.txt :
" Could not find a version that satisfies the requirement textwrap (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for textwrap (from -r requirements.txt (line 2)) "

-i'm using kali x64 -

**Comment by D4Vinci** [comment]
ignore that error and try to use the framework
it should work normally

**Comment by D4Vinci** [comment]
I removed this module to avoid the conflict.[check this out](https://github.com/D4Vinci/Dr0p1t-Framework/commit/d098bf21cd06f110b61b328e2417fa4c6866e3ca)
thank you for your concern

**Comment by ahmedkamal00** [comment]
sorry for confusing but it seems there is a problem in my system , i've tried install many python libraries but nothing changed..any help to fix this ?
"
 root@root:~/Dr0p1t-Framework# ./Dr0p1t.py
bash: ./Dr0p1t.py: Permission denied
root@root:~/Dr0p1t-Framework# python Dr0p1t.py
Traceback (most recent call last):
  File "Dr0p1t.py", line 2, in <module>
    from core.banners import random_banner as banner
ImportError: No module named core.banners
"

**Comment by D4Vinci** [comment]
first are you sure you are on python 3 ?
second Dr0p1t must run as root , try using :
`chmod 777 -R Dr0p1t-Framework`

**Comment by mosoltan** [comment]
try : 
python3 Dr0p1t.py

-on kali linux both Python 2.x and 3.x versions come pre-installed so just specify the proper version the tool supports also it will support python 2 soon .

**Comment by ahmedkamal00** [comment]
sorry i forgot to reply but i tested it and worked fine
