### ISSUE TITLE
PyInstaller Not Installed : Can't compile file to exe

### ISSUE THREAD

**Issue by XxoraxX** [D4Vinci/Dr0p1t-Framework#10]
Hi Karim

I tried ti install pyinstaller the one with the requirements file but i still have the same problem 
and the pyinstaller installed correctly .

**Comment by D4Vinci** [comment]
What's your os ?
And if you are on linux ,do you have wine installed and python 2.7 installed on wine ?
You can also use "--nocompile" option and then compile the script by yourself

**Comment by br1877** [comment]
I have the same problem. I'm trying to install Python 2.7, 3.4, 3.5 and pip install pyinstaller, but on each case I've got error:

`[*] Creating DR0P3R..
 [*] Adding kill antivirus function..
 [*] Adding startup function..
 [*] Adding task function..
 [*] Adding self destruct function..
 [*] Saving the final file..
 [!] PyInstaller not installed : Can't compile file to exe..
`
Tested on Ubuntu 16.04 and 14.04.

**Comment by D4Vinci** [comment]
I will update the framework to make it not requires wine to compile and work on both devices.
Stay Tuned

**Comment by dnkls** [comment]
The same problem(((

http://i.imgur.com/NGn708j.png

How to fix ?

**Comment by hostbob** [comment]
i thought i saw this pyinstaller was fixed in your 1.01 update i downloaded 1.2 but still having pyinstaller issue on kali linux and trying to windows is not working. when i use nocompile in builder and convert .py to .exe didn't run

**Comment by camilleeyries** [comment]
The solution: well, you've installed pyinstaller for the version of python associated with the "pip" command.

To install pyinstaller for the right version: 
```sh
# You need to have python version => 3
# Replace dr0p1t with the name of the folder where is stored the python script.
python3.4 -m venv dr0p1t
cd dr0p1t
source bin/activate
# You need to use the "pip" associated with your version of python
pip3.4 install pyinstaller
# Now run dr0p1t with the right python
python3.4 ./dr0p1t.py
```
It will just create an environnement for your python script.
You need to execute ```source bin/activate```each time you want to run the script.

**Comment by D4Vinci** [comment]
Does this solution worked for you guys ?
If this solution worked I will add it to the main README file 
 with mentioning you of course @camilleeyries

**Comment by hostbob** [comment]
first i can't understand your statement here

*Replace dr0p1t with the name of the folder where is stored the python script.*

and 

*python3.4 -m venv dr0p1t*

but after trying how i can fix this, i got this error in screen

http://prntscr.com/f6gvsi


Tested on windows 10, python3.4 installed


Regards

**Comment by camilleeyries** [comment]
To uglely fix that, @hostbob, find the file core/color.py,

then go to the line number 50, you'll find something like that:
```python
def print_banner(banner,info,c1,c2):
	global G, Y, B, R, W , M , C , end
	def cprint(text,info,c1,c2):
		print(c1+text+end)
		print(c2+info+end)
...snip...
```

replace this with that:
```python
def print_banner(banner,info,c1,c2):
	global G, Y, B, R, W , M , C , end
	end = '\33[97m'
	def cprint(text,info,c1,c2):
		print(c1+text+end)
		print(c2+info+end)
...snip...
```

Please do not include the "...snip..." statements.

Have a good day ^^

**Comment by hostbob** [comment]
got another error

http://prntscr.com/f7etpb

**Comment by D4Vinci** [comment]
Okay got it,I will check for all those typos in the framework so wait for the next update

**Comment by ProcessusThief** [comment]
Get it work when no compiled argument ;)


I created a payload with msfvenom with .exe extension. Then, used Dr0p1t with the --nocompile argument and tried to compile with pyinstaller afterward.
Bat, Powershell and VBS options throw errors.

Dr0p1t command : 
sudo python3.5 ./Dr0p1t.py /root/Bureau/virus.exe -b block_online_scan.bat -p Enable_PSRemoting.ps1 -v MakeHimBusy.vbs -s -t -k --nouac --upx --nocompile

Then, when tried "sudo pyinstaller Your_daily_malware_76.py", got that indentation error :

 File "/root/Bureau/Dr0p1t-Framework/output/Your_daily_malware_76.py", line 388
    x = p.stdout.read().decode()
                               ^
IndentationError: unindent does not match any outer indentation level



Then, to make it works : 

Dr0p1t command : 
sudo python3.5 ./Dr0p1t.py /root/Bureau/virus.exe -s -t -k --nouac --nocompile
And compiled with : 
pyinstaller output/Your_daily_malware_93.py

no errors appears :)

**Comment by D4Vinci** [comment]
And after that it won't woek also because Dr0p1t only takes urls for now :D
Every one wait for the next update version 1.3 I will fix all pyinstaller problems and rewrite most of the framework plus I will add many features it will be a huge update ^_^
Wait for it in the next couple days :D

**Comment by ProcessusThief** [comment]
i cross my fingers ;) thx for reply ;)

**Comment by D4Vinci** [comment]
Version 1.3 released and all this bugs fixed check it out :smile:
