### ISSUE TITLE
only on .ps1 file

### ISSUE THREAD

**Issue by nithilin** [D4Vinci/Dr0p1t-Framework#11]
[*] Compiling the final file to exe..
Traceback (most recent call last):
  File "./Dr0p1t.py", line 249, in <module>
    main()
  File "./Dr0p1t.py", line 229, in main
    file_name = get_executable()
  File "./Dr0p1t.py", line 83, in get_executable
    return os.listdir("dist")[0]
IndexError: list index out of range

**Comment by D4Vinci** [comment]
Every one wait for the next update version 1.3 I will fix all pyinstaller problems and rewrite most of the framework plus I will add many features it will be a huge update ^_^
Wait for it in the next couple days :D

**Comment by D4Vinci** [comment]
Version 1.3 released and all this bugs fixed check it out :smile:
