### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by hostbob** [D4Vinci/Dr0p1t-Framework#15]
Good job bro, keeping up with the project.

But the issue of pyinstaller is still the same. tested this on windows and kali linux also installing latest pyinstaller 3.2.1 still the same issue as in the below picture

![win-error](https://user-images.githubusercontent.com/7292467/27771146-b5f5ea92-5efd-11e7-878f-5300bce73375.png)
![kali-error](https://user-images.githubusercontent.com/7292467/27771147-b7b420ba-5efd-11e7-92f6-9534c3e3877f.png)

but using --nocompile works

**Comment by D4Vinci** [comment]
- Have you used install.sh on Linux?
- For windows try to uninstall and install pyinstaller again using pip

**Comment by hostbob** [comment]
![kali1](https://user-images.githubusercontent.com/7292467/27771398-954fa4a4-5f02-11e7-8197-e89c9064e026.png)

i have uninstall on windows before and reinstall the latest 3.2.1 still same error

**Comment by D4Vinci** [comment]
- What's the output of this command on your kali?
`wine /root/.wine/drive_c/Python27/python.exe /root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py`
- And this one on windows ?
`pyinstaller -h`

**Comment by hostbob** [comment]
![win](https://user-images.githubusercontent.com/7292467/27771496-5a3041d8-5f04-11e7-9fee-eb28957ed973.png)
![kil](https://user-images.githubusercontent.com/7292467/27771502-6a9652ce-5f04-11e7-90bb-7b192630bf2a.png)


Nothing show up on kali, and windows gives error in command

**Comment by D4Vinci** [comment]
Will from that appears that: 
- pyinstaller not installed on windows or try to add python folder and its scripts folder to system variable %path%
- Wine not installed correctly on Kali

**Comment by hostbob** [comment]
ok i add path to pyinstaller on windows and got this error 

Traceback (most recent call last):
  File "C:\Python34\dropit\Dr0p1t.py", line 309, in <module>
    main()
  File "C:\Python34\dropit\Dr0p1t.py", line 109, in main
    banner()
  File "C:\Python34\dropit\core\banners.py", line 44, in random_banner
    c2 = random.choice([G, Y, B, M , C])
NameError: global name 'M' is not defined

and how do i correctly install pyinstaller on KALI, maybe if i can see ur idea it might really help

**Comment by hostbob** [comment]
Hello guys, 

I have install Clean Kali and install wine using apt-get install wine and also install Python, Pip, Pyinstaller following this video

https://www.youtube.com/watch?v=YBLahOVIE_k

After installation i realize pyinstaller-script.py is not included in /.wine/drive_c/Python27/Scripts/ but i copied pyinstaller-script.py from Windows to pyinstaller folder then i got debug.txt error 

Can someone share their pyinstaller-script.py or show me the best way to have this fixed?

Thanks for your help guys
