### ISSUE TITLE
Python error from your code

### ISSUE THREAD

**Issue by hostbob** [D4Vinci/Dr0p1t-Framework#18]
I got this errors on Kali Linux and Windows

![kali](https://user-images.githubusercontent.com/7292467/27822192-a6d4e5e2-6059-11e7-9e11-378b80d0e5f6.png)
![error1](https://user-images.githubusercontent.com/7292467/27822193-a6d78fae-6059-11e7-9d63-120d1267cba7.png)
[debug.txt](https://github.com/D4Vinci/Dr0p1t-Framework/files/1121442/debug.txt)

**Comment by tugdualnicolas** [comment]
Did you installed pyinstaller on wine ? Try to install manualy

**Comment by hostbob** [comment]
How about the banner.py error on windows?

**Comment by tugdualnicolas** [comment]
I dont know sorry ^^'

**Comment by D4Vinci** [comment]
The error in banner.py is non-logical but I will try to find what's the cause

**Comment by D4Vinci** [comment]
It's the same issue in #15 why opening many issues !!

**Comment by hostbob** [comment]
sorry about that, i didn't recall same error just did now. but this issue is not understandable i am a bit confused. pyinstaller is installed on both Kali and windows, i also copied dr0p1t files into same folder of pyinstaller to be able to get rid of pyinstaller not installed but i am still getting banner.py error and on Kali a debug error which i included in my post. you can check the debug.txt i attach in the message to know where to have this fixed mate

**Comment by D4Vinci** [comment]
- For Kali pyinstaller dependencies not all installed or not installed correctly for some reasons so try this commands:
`sudo wine /root/.wine/drive_c/Python27/python.exe -m pip install --upgrade pip
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip uninstall pyinstaller
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip install pyinstaller`

- For windows, I will check banner.py ASAP

**Comment by D4Vinci** [comment]
Well, this issue will be considered as solved because you don't reply and reply to others issues instead !!

**Comment by hostbob** [comment]
sorry about that bro, i think since some other members are getting no error on kali i will reinstall Kali and do it afresh then. will update back

Thanks
