### ISSUE TITLE
EOL while scanning string literal

### ISSUE THREAD

**Issue by Bry-fi** [D4Vinci/Dr0p1t-Framework#20]
Worked fine before, updated and this error pops up.

Dr0p1t-Framework\temp\Dr0pp1r11.py", line 63
    pscode += "SelfDestruct"+"\n
                               ^
SyntaxError: EOL while scanning string literal

**Comment by Sirbu** [comment]
Got the same issue here. After a few tests it seem it is happening only when using the `--runas` option.

**Comment by D4Vinci** [comment]
Fixed in 1.3.1 update check it out!
