### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by hostbob** [D4Vinci/Dr0p1t-Framework#22]
Hello guys,

I have install Clean Kali and install wine using apt-get install wine and also install Python, Pip, Pyinstaller following this video

https://www.youtube.com/watch?v=YBLahOVIE_k

After installation i realize pyinstaller-script.py is not included in /.wine/drive_c/Python27/Scripts/ but i copied pyinstaller-script.py from Windows to pyinstaller folder then i got debug.txt error

https://user-images.githubusercontent.com/7292467/27992194-b849bba8-6442-11e7-8753-93158b59e765.png

https://user-images.githubusercontent.com/7292467/27992195-b9bb8462-6442-11e7-8e9c-2ce3caf20c36.png

Can someone share their pyinstaller-script.py or show me the best way to have this fixed?

Thanks for your help guys

**Comment by D4Vinci** [comment]
If You installed every thing right, you will have pyinstaller-script.py in your wine !!
