### ISSUE TITLE
PyInstaller not installed : Can't compile file to exe..

### ISSUE THREAD

**Issue by jackjackamerica** [D4Vinci/Dr0p1t-Framework#27]
hi there i'm using ubuntu 16.04 LTS
it says pyyinstaller doesn't exist however it exists 
and also there's no output in ouput folder
what should i do?

 [*] Creating DR0P3R..
 [*] Adding kill antivirus function..
 [*] Adding startup function..
 [*] Adding task function..
 [*] Adding add2profile function..
 [*] Adding disable UAC function..
 [*] Adding self destruct function..
 [*] Adding clear eventlog function..
 [*] Saving the final file..
 [!] PyInstaller not installed : Can't compile file to exe..
 [*] Finished and saved our Dr0pp3r as Dr0pp1r68 in output folder ( happy hunting )

root@123456:/opt/Dr0p1t-Framework# pip install PyInstaller
Requirement already satisfied: PyInstaller in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from PyInstaller)

**Comment by tugdualnicolas** [comment]
You need to install pyinstaller in wine

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jackjackamerica** [comment]
@tugdualnicolas can u help me how to do that?
i donno how to do
