### ISSUE TITLE
pyinstaller issue

### ISSUE THREAD

**Issue by hostbob** [D4Vinci/Dr0p1t-Framework#29]
i have gone through series of understanding why i can't compile or make the dr0p1t to work. but i think the issue is no pyinstaller-script in pyinstaller folder. if you can share pyinstaller-script.py or share how to have that fixed will make user facing this issue make use of Dr0p1t

**Comment by D4Vinci** [comment]
instead of opening the same issue, again and again, you can wait until the next update (version 2) !!
It will be written from scratch so it should solve your weird problems!
Goodbye and Stop Opening Issues!!!
