### ISSUE TITLE
Error installin

### ISSUE THREAD

**Issue by nourziady** [D4Vinci/Dr0p1t-Framework#3]
i got this error while installing dropper on victim machine

![image](https://cloud.githubusercontent.com/assets/8343453/22944424/5408d148-f2f9-11e6-925c-f0069973fb3a.png)

**Comment by D4Vinci** [comment]
You can try removing "--noconsole" from the varaible "command" in the main script "Dr0p1t.py" line 78 or wait for my fix I will handle this and let you know

**Comment by nourziady** [comment]
got same error but this time in console 

> Error loading Python DLL: C:\Users\PiTnS\AppData\Local\Temp\_MEI45242\python35.d
ll (error code 193) <

as i tried to run it normally and found command prompt run and exit then i tried it from console

**Comment by D4Vinci** [comment]
try running the framework and then converting the script by yourself from the temp folder by command
```
pyinstaller -F your_daily_malware.py
```
and let me know what happened and also try checking if pyinstaller on the last version with pip by command
```
pip install pyinstaller --upgrade
```
if this didn't work try reinstalling pyinstaller by 
```
pip uninstall pyinstaller
pip install pyinstaller
```
if this all didn't work let me know also

**Comment by nourziady** [comment]
nothing from above solved it :(

**Comment by D4Vinci** [comment]
Error code 193 means the exe file is corrupted for some reason
have you used `--upx` option ?
if yes try to not use it and let me know the result

**Comment by nourziady** [comment]
tried with and without and same result

**Comment by D4Vinci** [comment]
try adding `--noupx ` to the command varaible like before and let me know

**Comment by nourziady** [comment]
same result too
command var now `command = "pyinstaller --noconsole --noupx -F {} "`

**Comment by D4Vinci** [comment]
I have told you before to remove `--noconsole` from the command varaible!

The error from pyinstaller,it can't find python35.dll for some reason maybe when you switched back from python 3.6 to 3.5 you have missed some thing or didn't reboot your device after the uninstalling!

Try search your device for python35.dll file and take a copy from it to the temp folder or to the python executable folder so if you installed it in C:\Python35 copy the file to it and the pyinstaller folder
you can try this code to find the file
`C:\>dir /s /b "python35.dll"`

**Comment by nourziady** [comment]
to be clear i tried to run it with --noconsole and without, i'm running dropper on another machine

here's the temp folder screen show when trying to run it
![image](https://cloud.githubusercontent.com/assets/8343453/22946769/12ee5a18-f301-11e6-9404-fdd726a6df57.png)

its already have python35.dll file

**Comment by D4Vinci** [comment]
Do you have MS Visual C++ Redistributable 2015 installed on your device ?

**Comment by D4Vinci** [comment]
if you have a GNU/linux machine try using the framework on it and see if the same result

**Comment by D4Vinci** [comment]
also try replacing `--noconsole` with `--windowed` in command varaible

**Comment by D4Vinci** [comment]
I will put temporary solution in the next update that would help

**Comment by D4Vinci** [comment]
The framework updated thank you
