### ISSUE TITLE
Install under Kali

### ISSUE THREAD

**Issue by psychomad** [D4Vinci/Dr0p1t-Framework#4]
Hi.
Made everything as u wrote and i got this after launch:

 ./Dr0p1t.py
from: too many arguments
from: too many arguments
from: too many arguments
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
./Dr0p1t.py: riga 7: errore di sintassi vicino al token non atteso "("
./Dr0p1t.py: riga 7: `parser = argparse.ArgumentParser('

From a ssh console

If i launch directly on the Kali computer i have the same except:
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.

Any suggestion?

**Comment by D4Vinci** [comment]
Are you sure you are on python 3 ?

**Comment by psychomad** [comment]
Yes i checked version in use and i forced to use it just to be sure

**Comment by D4Vinci** [comment]
Try adding this line to the begin at Dr0p1t,py:
`#!/usr/bin/python3`

**Comment by psychomad** [comment]
It works! thanks a lot
(sorry but im totally newbie with python going to learn more)
Thanks for good job

**Comment by D4Vinci** [comment]
No problem and have a good time
