### ISSUE TITLE
Add cross-compile

### ISSUE THREAD

**Issue by 4w4k3** [D4Vinci/Dr0p1t-Framework#5]
When I try generate dropper using linux, he not work to windows.

**Comment by D4Vinci** [comment]
Wait for the next update today,I will do alot of bug fixing

**Comment by D4Vinci** [comment]
Check now

**Comment by jvzior** [comment]
Hello BROW . 
ERROR COMPILE :/

 [*] Creating DR0P3R..
 [*] Adding startup function..
 [*] Adding task function..
 [*] Adding kill antivirus function..
 [*] Saving the final file..
 [*] Compiling the final file to exe..
 [*] Compressing the final file..
Traceback (most recent call last):
  File "Dr0p1t.py", line 216, in <module>
    main()
  File "Dr0p1t.py", line 205, in main
    make_copy( os.path.join("temp","dist",file_name),os.path.join("output",file_name) )
  File "Dr0p1t.py", line 53, in make_copy
    old_file = open( old,"rb" )
IOError: [Errno 2] No such file or directory: 'temp/dist/Your_daily_malware_73'

**Comment by D4Vinci** [comment]
Issue fixed thank you 😃
