### ISSUE TITLE
PyInstaller Problem Linux Mint

### ISSUE THREAD

**Issue by Gitworm** [D4Vinci/Dr0p1t-Framework#9]
You guys should have a look at this PyInstaller part of the Main python script I guess,  tried to use it in Linux mint but it keeps telling me that PyInstaller wouldn't be installed and therefore it can't make the executable. Guess the problem lays in the fact that u are making use of PyInstaller in wine but mine is installed directly in Linux Mint and I don't need wine for using it.

**Comment by D4Vinci** [comment]
There was a problem before in pyinstaller on linux and it solved by using wine but you can use `--nocompile ` option and then compile the script by your self .
Thank you :smile:
